package edu.jaco.fin_stater.transaction;

public enum TransactionSubcategory {
    SPOZYWCZE_ZAMAWIANE,
    SPOZYWCZE_SLODKOSCI,
    SPOZYWCZE_MARKETY,
    SPOZYWCZE_OTHER,
    CIALO_ZDROWIE,
    CIALO_HIGIENA,
    CIALO_BEAUTY,
    CIALO_OTHER,
    TRANSPORT_AUTO_PALIWO,
    TRANSPORT_AUTO_SERWIS,
    TRANSPORT_BILETY,
    TRANSPORT_PARKING,
    TRANSPORT_OTHER,
    DZIECI_PLACOWKI,
    DZIECI_OTHER,
    OPLATY_SUBSKRYPCJE,
    OPLATY_OTHER,
    OTHER
}
